.circleci/config.yml
README.md

Add .circleci/config.yml

---

README.md

Adds dictionary downloading to README

Adds dictionary downloading to README

---

Dockerfile

It allows to run the App into a docker container:
To build the image: docker build --tag tt-search-query-parser .
To run the image:   docker run -d -p 5000:5000 tt-search-query-parser
https://transformuk.atlassian.net/browse/HOTT-1669
To isolate the app from the local and production environment
To easily run test in CI

HOTT-1669 Add Dockerfile

---

.editorconfig
.gitignore
README.md
flaskr/__init__.py
flaskr/tokenizer.py
tests/conftest.py
tests/functional/test_get_healthcheck.py
tests/functional/test_get_tokens.py

https://transformuk.atlassian.net/browse/HOTT-1690
- This is required so we can verify the application is running and check the current sha for release

HOTT-1690: Adds healthcheck endpoint

---

flaskr/__init__.py

Remove duplication for the API prefix "/api/search/" .
To remove duplication and reduce chances to make copy/paste mistakes.

Remove duplication for the API prefix "/api/search/" .

---

.circleci/config.yml
.flake8
tests/conftest.py

HOTT-<TODO>
- Code consistency

Adds linting checks to project

---

.tool-versions

Bump local python to match Dockerfile

---

requirements/common.txt

Bumps spacy and thinc

---

.circleci/config.yml
flaskr/__init__.py
tests/functional/test_get_tokens.py

HOTT-<TODO>
- This is required for the 'Did you mean?' functionality

Support disabling spelling corrections

---

.circleci/config.yml
.tool-versions
Dockerfile
README.md
requirements/common.txt

Reverts trade-tariff/trade-tariff-search-query-parser#90

Revert "Bump python from 3.10.7-slim-bullseye to 3.11.1-slim-bullseye"

---

flaskr/__init__.py
flaskr/spelling_corrector.py
tests/unit/test_spelling_corrector.py

https://transformuk.atlassian.net/browse/HOTT-2372
- This avoids coupling boot with loading the spelling model file and forcing all local users to have their environment configured

HOTT-2372: Lazy load the spelling model

---

.circleci/config.yml
.gitignore
.tool-versions
Dockerfile
requirements/test.txt

https://transformuk.atlassian.net/browse/HOTT-2697
- This is part of a wider rollout of us knowing when test coverage has dropped

HOTT-2697: Adds coverage threshold check for tests

---

flaskr/tokenizer.py
tests/functional/test_get_tokens.py

https://transformuk.atlassian.net/browse/HOTT-2813
- This is required to properly handle quoted tokens in the backend

HOTT-2813: Support multi-word quoted tokens

---

flaskr/__init__.py
tests/functional/test_healthz.py

[HOTT-3652](https://transformuk.atlassian.net/browse/HOTT-3652)
- Added isolated healthcheck route under `/healthcheckz`.
- Added simple test for coverage.
- We need this route for container healthchecking in ECS.

HOTT-3652: Create Isolated Healthcheck

---

.circleci/config.yml
terraform/backends/production.tfbackend
terraform/backends/staging.tfbackend
terraform/config_production.tfvars
terraform/config_staging.tfvars
terraform/data.tf

[HOTT-3898](https://transformuk.atlassian.net/browse/HOTT-3898)
- Added configuration to deploy service to `staging` and `production` environments.
- Made significant changes to the CircleCi workflows to achieve this.

HOTT-3898: Promote to Upper Environments

---

.circleci/config.yml
terraform/backends/development.tfbackend

https://transformuk.atlassian.net/browse/HOTT-3919

HOTT-3919: Fixes production release

---

.circleci/config.yml

BAU: Fixes typo in smoketests

---

requirements/common.txt

Reverts trade-tariff/trade-tariff-search-query-parser#271

Revert "Bump thinc from 8.1.10 to 8.2.1"

---

requirements/common.txt

Reverts trade-tariff/trade-tariff-search-query-parser#279

Revert "Bump s3transfer from 0.6.0 to 0.7.0"

---

terraform/.terraform.lock.hcl
terraform/README.md
terraform/data.tf
terraform/iam.tf
terraform/main.tf

BAU
- This is required to make sure we're propagating/able to view errors

BAU: Adds sentry configuration

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-4597

HOTT-4597: Update smoketest context

---

.circleci/config.yml

[HOTT-4598](https://transformuk.atlassian.net/browse/HOTT-4598)
- Updated releases context in CircleCi config.
- We now have a new context that we can use for releases, so we'll want to use this.

HOTT-4598: Update CircleCi Contexts

---

Dockerfile

BAU
- This is needed to make sure the healthcheck runs

BAU: Improve HEALTHCHECK

---

.markdownlint.yaml
.pre-commit-config.yaml
README.md

BAU
- To reduce the overheads of conversation and feedback loops that come from ci
- To improve security by blocking credentials from being committed

BAU: Consolidate pre-commit configuration
